server:
  port: 8080
  servlet:
    context-path: /lingzhen

spring:
  datasource:
    url: jdbc:mysql://172.16.184.240:3306/life
    username: root
    password: Jingzhidb123!

#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations[0]: classpath:mapper/*.xml
  mapper-locations[1]: classpath:mapper/**/*.xml

#springboot-日志
logging:
  level:
    com.lingzhen.myproject.lifefolder: debug
  file:
    path: "filefolder_log"

# 文件上传地址
fileUploadPath: /home/data/project/lifeFolder/file/