server:
  port: 8080
  servlet:
    context-path: /lingzhen

spring:
  datasource:
    #url: jdbc:mysql://101.37.78.234:3306/life?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    url: jdbc:mysql://101.37.78.234:3306/life
    username: root
    password: Jingzhidb123!
    #阿里连接池Druid
    druid:
      initial-siz: 3
      max-wait=: 3000

#mybatis配置
#http://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations[0]: classpath:mapper/*.xml
  mapper-locations[1]: classpath:mapper/**/*.xml

