server:
  port: 8081
  servlet:
    context-path: /rdm

spring:
  #配置热部署
  devtools:
    restart:
      enabled: true

#springboot-日志
#https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-custom-log-levels
logging:
  level:
    com.lingzhen.rdm: debug
